//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.Client.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.Client.Core.Resources.ClientResources", typeof(ClientResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not validate the Email Address and Password you supplied..
        /// </summary>
        public static string Auth_FailedLogin {
            get {
                return ResourceManager.GetString("Auth_FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has been Changed.
        /// </summary>
        public static string ChangePassword_Confirmed {
            get {
                return ResourceManager.GetString("ChangePassword_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ChangePassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -confirm your new password-.
        /// </summary>
        public static string ChangePassword_ConfirmNewPassword_WaterMark {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmNewPassword_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is a Required Field.
        /// </summary>
        public static string ChangePassword_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your New Password and Confrim Password Must Match.
        /// </summary>
        public static string ChangePassword_NewConfirmMatch {
            get {
                return ResourceManager.GetString("ChangePassword_NewConfirmMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePassword_NewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter a new password-.
        /// </summary>
        public static string ChangePassword_NewPassword_WaterMark {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is a Required Field.
        /// </summary>
        public static string ChangePassword_NewPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePassword_NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string ChangePassword_OldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your old password-.
        /// </summary>
        public static string ChangePassword_OldPassword_WaterMark {
            get {
                return ResourceManager.GetString("ChangePassword_OldPassword_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is a Required Field.
        /// </summary>
        public static string ChangePassword_OldPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePassword_OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Password.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your password-.
        /// </summary>
        public static string Common_Email_Password {
            get {
                return ResourceManager.GetString("Common_Email_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your email address-.
        /// </summary>
        public static string Common_Email_Watermark {
            get {
                return ResourceManager.GetString("Common_Email_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Common_EmailAddress {
            get {
                return ResourceManager.GetString("Common_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error communicating with the server.   Please try again later..
        /// </summary>
        public static string Common_ErrorCommunicatingWithServer {
            get {
                return ResourceManager.GetString("Common_ErrorCommunicatingWithServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Common_GetStarted {
            get {
                return ResourceManager.GetString("Common_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Key is already in use, please select a different Key..
        /// </summary>
        public static string Common_KeyInUse {
            get {
                return ResourceManager.GetString("Common_KeyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Common_Login {
            get {
                return ResourceManager.GetString("Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Common_Logout {
            get {
                return ResourceManager.GetString("Common_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There does not appear to be a connection to the internet, please check your connectoin and try again .ater..
        /// </summary>
        public static string Common_NoConnection {
            get {
                return ResourceManager.GetString("Common_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Common_Submit {
            get {
                return ResourceManager.GetString("Common_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string InviteUser_Email {
            get {
                return ResourceManager.GetString("InviteUser_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -send invitation to email-.
        /// </summary>
        public static string InviteUser_Email_Watermark {
            get {
                return ResourceManager.GetString("InviteUser_Email_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an Invitation to some one to join the [ORGNAME] organization.  They will be prompted to create a new user if they don&apos;t already have one, or will be added to your organization if they do..
        /// </summary>
        public static string InviteUser_Help {
            get {
                return ResourceManager.GetString("InviteUser_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message.
        /// </summary>
        public static string InviteUser_Message {
            get {
                return ResourceManager.GetString("InviteUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -add a message to the invitation-.
        /// </summary>
        public static string InviteUser_Message_Watermark {
            get {
                return ResourceManager.GetString("InviteUser_Message_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string InviteUser_Name {
            get {
                return ResourceManager.GetString("InviteUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -name of individual to invite-.
        /// </summary>
        public static string InviteUser_Name_Watermark {
            get {
                return ResourceManager.GetString("InviteUser_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite User.
        /// </summary>
        public static string InviteUser_Submit {
            get {
                return ResourceManager.GetString("InviteUser_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite a New User.
        /// </summary>
        public static string InviteUser_Title {
            get {
                return ResourceManager.GetString("InviteUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least 8 characters, with at least one number and one upper case and one lower case letter.
        /// </summary>
        public static string Password_Requirements {
            get {
                return ResourceManager.GetString("Password_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Register_Confirm_Password {
            get {
                return ResourceManager.GetString("Register_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -confirm your password-.
        /// </summary>
        public static string Register_ConfirmPassword_Watermark {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string Register_Email_Invalid {
            get {
                return ResourceManager.GetString("Register_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is a Required FIeld.
        /// </summary>
        public static string Register_Email_Required {
            get {
                return ResourceManager.GetString("Register_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your email address-.
        /// </summary>
        public static string Register_Email_WaterMark {
            get {
                return ResourceManager.GetString("Register_Email_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Register_FirstName {
            get {
                return ResourceManager.GetString("Register_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is a Required Field.
        /// </summary>
        public static string Register_FirstName_Required {
            get {
                return ResourceManager.GetString("Register_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your first name-.
        /// </summary>
        public static string Register_FirstName_WaterMark {
            get {
                return ResourceManager.GetString("Register_FirstName_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Register_LastName {
            get {
                return ResourceManager.GetString("Register_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is a Required Field.
        /// </summary>
        public static string Register_LastName_Required {
            get {
                return ResourceManager.GetString("Register_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your last name-.
        /// </summary>
        public static string Register_LastName_WaterMark {
            get {
                return ResourceManager.GetString("Register_LastName_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password must match..
        /// </summary>
        public static string Register_Password_Confirm_NoMatch {
            get {
                return ResourceManager.GetString("Register_Password_Confirm_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is a Required Field.
        /// </summary>
        public static string Register_Password_Required {
            get {
                return ResourceManager.GetString("Register_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter a password-.
        /// </summary>
        public static string Register_Password_Watermark {
            get {
                return ResourceManager.GetString("Register_Password_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ResetPassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ResetPassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -confirm your new password-.
        /// </summary>
        public static string ResetPassword_ConfirmNewPassword_Watermark {
            get {
                return ResourceManager.GetString("ResetPassword_ConfirmNewPassword_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter a new password-.
        /// </summary>
        public static string ResetPassword_NewPassword_Watermark {
            get {
                return ResourceManager.GetString("ResetPassword_NewPassword_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword_Submit {
            get {
                return ResourceManager.GetString("ResetPassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your Password.
        /// </summary>
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string SendResetPasswordLink_Email {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your accounts email address-.
        /// </summary>
        public static string SendResetPasswordLink_Email_Watermark {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Email_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you forgot your password, you can have a link sent to your email address to let you reset it to a new one..
        /// </summary>
        public static string SendResetPasswordLink_Help {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your account exissts an email will be sent to our email address with instructions on how to reset your password.
        /// </summary>
        public static string SendResetPasswordLink_Message {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your Password.
        /// </summary>
        public static string SendResetPasswordLink_Title {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Link.
        /// </summary>
        public static string SendRestPasswordLink_Send {
            get {
                return ResourceManager.GetString("SendRestPasswordLink_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Code.
        /// </summary>
        public static string Verify_ConfirmCode {
            get {
                return ResourceManager.GetString("Verify_ConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your email address has been confirmed..
        /// </summary>
        public static string Verify_Email_Confirmed {
            get {
                return ResourceManager.GetString("Verify_Email_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email message has been sent and and should arrive in your inbox shortly.  If you don&apos;t receive this in a few minutes please check other folders it may arrive in. .
        /// </summary>
        public static string Verify_EmailSent {
            get {
                return ResourceManager.GetString("Verify_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Verify_PhoneNumber {
            get {
                return ResourceManager.GetString("Verify_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your phone number-.
        /// </summary>
        public static string Verify_PhoneNumber_Watermark {
            get {
                return ResourceManager.GetString("Verify_PhoneNumber_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recevied Code.
        /// </summary>
        public static string Verify_ReceivedCode {
            get {
                return ResourceManager.GetString("Verify_ReceivedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter 6 digit code-.
        /// </summary>
        public static string Verify_ReceivedCode_Watermark {
            get {
                return ResourceManager.GetString("Verify_ReceivedCode_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Confirmation Email.
        /// </summary>
        public static string Verify_SendEmail {
            get {
                return ResourceManager.GetString("Verify_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS Confirmation.
        /// </summary>
        public static string Verify_SendSMS {
            get {
                return ResourceManager.GetString("Verify_SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your phone number has been confirmed..
        /// </summary>
        public static string Verify_SMS_Confirmed {
            get {
                return ResourceManager.GetString("Verify_SMS_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SMS message has been sent, please check your phone and enter the code you receive..
        /// </summary>
        public static string Verify_SMSSent {
            get {
                return ResourceManager.GetString("Verify_SMSSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your Identity.
        /// </summary>
        public static string Verify_Title {
            get {
                return ResourceManager.GetString("Verify_Title", resourceCulture);
            }
        }
    }
}
