//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.DeviceManager.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeviceManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeviceManagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.DeviceManager.Core.Resources.DeviceManagerResources", typeof(DeviceManagerResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manager.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Common_GetStarted {
            get {
                return ResourceManager.GetString("Common_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search by device id.
        /// </summary>
        public static string DeviceExplorer_SearchWatermark {
            get {
                return ResourceManager.GetString("DeviceExplorer_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Explorer.
        /// </summary>
        public static string DeviceExplorer_Title {
            get {
                return ResourceManager.GetString("DeviceExplorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Device Type.
        /// </summary>
        public static string DeviceTypePicker_Title {
            get {
                return ResourceManager.GetString("DeviceTypePicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Device.
        /// </summary>
        public static string ManageDevice_Title {
            get {
                return ResourceManager.GetString("ManageDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Attributes.
        /// </summary>
        public static string MonitorDevice_Attributes {
            get {
                return ResourceManager.GetString("MonitorDevice_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        public static string MonitorDevice_DeviceId {
            get {
                return ResourceManager.GetString("MonitorDevice_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Information.
        /// </summary>
        public static string MonitorDevice_DeviceInformation {
            get {
                return ResourceManager.GetString("MonitorDevice_DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Contact.
        /// </summary>
        public static string MonitorDevice_LastContact {
            get {
                return ResourceManager.GetString("MonitorDevice_LastContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MonitorDevice_Messages {
            get {
                return ResourceManager.GetString("MonitorDevice_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -select output command-.
        /// </summary>
        public static string MonitorDevice_SelectOutputCommand {
            get {
                return ResourceManager.GetString("MonitorDevice_SelectOutputCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string MonitorDevice_Send {
            get {
                return ResourceManager.GetString("MonitorDevice_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machines.
        /// </summary>
        public static string MonitorDevice_StateMachines {
            get {
                return ResourceManager.GetString("MonitorDevice_StateMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MonitorDevice_Status {
            get {
                return ResourceManager.GetString("MonitorDevice_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Device.
        /// </summary>
        public static string MonitorDevice_Title {
            get {
                return ResourceManager.GetString("MonitorDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision Device.
        /// </summary>
        public static string ProvisionDevice_Title {
            get {
                return ResourceManager.GetString("ProvisionDevice_Title", resourceCulture);
            }
        }
    }
}
